import { createClient } from '@supabase/supabase-js';
import pkg from 'electron-updater';
import log from 'electron-log';
import { createAnthropic } from '@ai-sdk/anthropic';
import { tool, streamText, NoSuchToolError, generateObject, RetryError } from 'ai';
import { z } from 'zod';
import fg from 'fast-glob';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { createOpenAI } from '@ai-sdk/openai';
import mime from 'mime-lite';
import { detect } from 'detect-port';
import { Client } from '@trainloop/sdk';
import prettier from 'prettier';
import { subscribe } from '@parcel/watcher';
import * as pty from 'node-pty';
import { parse, quote } from 'shell-quote';
import { Project, Node, ts } from 'ts-morph';
import download from 'download';
import 'freestyle-sandboxes';
import { isBinary } from 'istextorbinary';

console.log('Success');
